// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using digitalArsv1;

#nullable disable

namespace digitalArsv1.Migrations
{
    [DbContext(typeof(DigitalArsContext))]
    [Migration("20250529220115_initialNicooo")]
    partial class initialNicooo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Usuario", b =>
                {
                    b.Property<int>("nro_cliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("nro_cliente");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("nro_cliente"));

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("apellido");

                    b.Property<string>("direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("direccion");

                    b.Property<bool>("estado")
                        .HasColumnType("bit")
                        .HasColumnName("estado");

                    b.Property<string>("mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mail");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nombre");

                    b.Property<string>("password_hash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("telefono");

                    b.Property<string>("tipo_cliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("nro_cliente");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("digitalArsv1.Models.Cuenta", b =>
                {
                    b.Property<int>("nro_cuenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("nro_cuenta");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("nro_cuenta"));

                    b.Property<string>("CBU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CBU");

                    b.Property<bool>("estado")
                        .HasColumnType("bit")
                        .HasColumnName("estado");

                    b.Property<int>("nro_cliente")
                        .HasColumnType("int")
                        .HasColumnName("nro_cliente");

                    b.Property<string>("producto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("producto");

                    b.Property<string>("rol_cta")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("rol_cta");

                    b.HasKey("nro_cuenta");

                    b.HasIndex("nro_cliente");

                    b.ToTable("Cuenta", (string)null);
                });

            modelBuilder.Entity("digitalArsv1.Models.Movimiento", b =>
                {
                    b.Property<int>("id_trx")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_trx");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_trx"));

                    b.Property<int?>("codigo_transaccion")
                        .HasColumnType("int")
                        .HasColumnName("codigo_transaccion");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha");

                    b.Property<decimal>("monto")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("monto");

                    b.Property<int?>("nro_cuenta_dest")
                        .HasColumnType("int")
                        .HasColumnName("nro_cuenta_dest");

                    b.Property<int>("nro_cuenta_orig")
                        .HasColumnType("int")
                        .HasColumnName("nro_cuenta_orig");

                    b.HasKey("id_trx");

                    b.HasIndex("codigo_transaccion");

                    b.HasIndex("nro_cuenta_dest");

                    b.HasIndex("nro_cuenta_orig");

                    b.ToTable("Movimiento", (string)null);
                });

            modelBuilder.Entity("digitalArsv1.Models.Permiso", b =>
                {
                    b.Property<int>("nro_usuario")
                        .HasColumnType("int")
                        .HasColumnName("nro_usuario")
                        .HasColumnOrder(0);

                    b.Property<string>("acceso")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("acceso")
                        .HasColumnOrder(1);

                    b.HasKey("nro_usuario", "acceso");

                    b.ToTable("Permisos", (string)null);
                });

            modelBuilder.Entity("digitalArsv1.Models.Transaccion", b =>
                {
                    b.Property<int>("codigo_transaccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("codigo_transaccion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("codigo_transaccion"));

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descripcion");

                    b.HasKey("codigo_transaccion");

                    b.ToTable("Transaccion", (string)null);
                });

            modelBuilder.Entity("digitalArsv1.Models.Cuenta", b =>
                {
                    b.HasOne("Usuario", "Usuario")
                        .WithMany("Cuentas")
                        .HasForeignKey("nro_cliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("digitalArsv1.Models.Movimiento", b =>
                {
                    b.HasOne("digitalArsv1.Models.Transaccion", "Transaccion")
                        .WithMany("Movimientos")
                        .HasForeignKey("codigo_transaccion")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("digitalArsv1.Models.Cuenta", "CuentaDest")
                        .WithMany("MovimientosDestino")
                        .HasForeignKey("nro_cuenta_dest")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("digitalArsv1.Models.Cuenta", "CuentaOrig")
                        .WithMany("MovimientosOrigen")
                        .HasForeignKey("nro_cuenta_orig")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CuentaDest");

                    b.Navigation("CuentaOrig");

                    b.Navigation("Transaccion");
                });

            modelBuilder.Entity("digitalArsv1.Models.Permiso", b =>
                {
                    b.HasOne("Usuario", "Usuario")
                        .WithMany("Permisos")
                        .HasForeignKey("nro_usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Usuario", b =>
                {
                    b.Navigation("Cuentas");

                    b.Navigation("Permisos");
                });

            modelBuilder.Entity("digitalArsv1.Models.Cuenta", b =>
                {
                    b.Navigation("MovimientosDestino");

                    b.Navigation("MovimientosOrigen");
                });

            modelBuilder.Entity("digitalArsv1.Models.Transaccion", b =>
                {
                    b.Navigation("Movimientos");
                });
#pragma warning restore 612, 618
        }
    }
}
